# Arnavs tmux config
# Use with Neovim lazyvim defaults with Supertab :)

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind '\' split-window -h
bind '-' split-window -v
unbind '"'
unbind %

# switch panes using vim pane navigation bindings
bind 'h' select-pane -L
bind 'j' select-pane -D
bind 'k' select-pane -U
bind 'l' select-pane -R

# panes
set -g pane-border-style 'fg=gray'
set -g pane-active-border-style 'fg=blue'

# status clock
set -g status-right '%Y-%m-%d %I:%M %p'
